// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCBuilder.Services.ComponentsAPI.Data;

#nullable disable

namespace PCBuilder.Service.ComponentsAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260326074345_newthings")]
    partial class newthings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ExternalVolumeLiters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IncludedPowerSupplyWatts")
                        .HasColumnType("int");

                    b.Property<int?>("Internal35Bays")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SidePanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.CaseAccessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FormFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CaseAccessories", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.CaseFan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AirflowMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AirflowMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NoiseLevelMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NoiseLevelMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pwm")
                        .HasColumnType("bit");

                    b.Property<int?>("RpmMax")
                        .HasColumnType("int");

                    b.Property<int?>("RpmMin")
                        .HasColumnType("int");

                    b.Property<int>("SizeMM")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("ChassiCooling", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Cpu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BoostClock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CoreClock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CoreCount")
                        .HasColumnType("int");

                    b.Property<string>("IntegratedGraphics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Microarchitecture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Tdp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("CPUs", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.CpuCooler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAio")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NoiseLevelMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NoiseLevelMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RadiatorSize")
                        .HasColumnType("int");

                    b.Property<int?>("RpmMax")
                        .HasColumnType("int");

                    b.Property<int?>("RpmMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("CPUCoolers", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.ExternalHardDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CapacityGB")
                        .HasColumnType("bigint");

                    b.Property<string>("Interface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PricePerGB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExternalStorages", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.FanController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChannelWattage")
                        .HasColumnType("int");

                    b.Property<int?>("Channels")
                        .HasColumnType("int");

                    b.Property<string>("FormFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pwm")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("FanControllers", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.FormFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormFactors", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Headphones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnclosureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FrequencyMaxKhz")
                        .HasColumnType("int");

                    b.Property<int?>("FrequencyMinHz")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<bool>("Microphone")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Wireless")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Headsets", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.InternalHardDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CacheMB")
                        .HasColumnType("int");

                    b.Property<long>("CapacityGB")
                        .HasColumnType("bigint");

                    b.Property<string>("FormFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storages", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Backlit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Connection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tenkeyless")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Keyboards", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.MemoryKit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CasLatency")
                        .HasColumnType("int");

                    b.Property<decimal?>("FirstWordLatency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ModulesCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpeedMTs")
                        .HasColumnType("int");

                    b.Property<int>("TotalCapacityGB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("RAMModules", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspectRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RefreshRateHz")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("int");

                    b.Property<decimal?>("ResponseTimeMs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ScreenSizeInches")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Monitors", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormFactorId")
                        .HasColumnType("int");

                    b.Property<bool?>("HasWiFi")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxMemoryGB")
                        .HasColumnType("int");

                    b.Property<int?>("MemorySlots")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FormFactorId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Socket");

                    b.ToTable("Motherboards", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Mouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Connection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandOrientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDpi")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Mice", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.OperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Architecture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxMemoryGB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.PowerSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EfficiencyRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Modular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("PSUs", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.SoundCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DigitalAudioBits")
                        .HasColumnType("int");

                    b.Property<string>("Interface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SampleRateKhz")
                        .HasColumnType("int");

                    b.Property<int?>("SnrDb")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SoundCards", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Speakers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FrequencyMaxKhz")
                        .HasColumnType("int");

                    b.Property<int?>("FrequencyMinHz")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Wattage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Speakers", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Ups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapacityVa")
                        .HasColumnType("int");

                    b.Property<int?>("CapacityWatts")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("UPS", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.VideoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoostClock")
                        .HasColumnType("int");

                    b.Property<string>("Chipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoreClock")
                        .HasColumnType("int");

                    b.Property<int?>("LengthMM")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryGB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("GPUs", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Webcam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Connection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocusType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FovDegrees")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Resolutions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportedOs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Webcams", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Case", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("Cases")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.CaseFan", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("CaseFans")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Cpu", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", "Manufacturer")
                        .WithMany("Cpus")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.CpuCooler", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("CpuCoolers")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.FanController", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("FanControllers")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Headphones", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("Headphones")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Keyboard", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("Keyboards")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.MemoryKit", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("MemoryKits")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Monitor", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("Monitors")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Motherboard", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.FormFactor", "FormFactor")
                        .WithMany()
                        .HasForeignKey("FormFactorId");

                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", "Manufacturer")
                        .WithMany("Motherboards")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("FormFactor");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Mouse", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("Mice")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.PowerSupply", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("PowerSupplies")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Speakers", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("Speakers")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.VideoCard", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", "Manufacturer")
                        .WithMany("VideoCards")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Webcam", b =>
                {
                    b.HasOne("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", null)
                        .WithMany("Webcams")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("PCBuilder.Service.ComponentsAPI.Models.Manufacturer", b =>
                {
                    b.Navigation("CaseFans");

                    b.Navigation("Cases");

                    b.Navigation("CpuCoolers");

                    b.Navigation("Cpus");

                    b.Navigation("FanControllers");

                    b.Navigation("Headphones");

                    b.Navigation("Keyboards");

                    b.Navigation("MemoryKits");

                    b.Navigation("Mice");

                    b.Navigation("Monitors");

                    b.Navigation("Motherboards");

                    b.Navigation("PowerSupplies");

                    b.Navigation("Speakers");

                    b.Navigation("VideoCards");

                    b.Navigation("Webcams");
                });
#pragma warning restore 612, 618
        }
    }
}
